# -*- coding: utf-8 -*-
"""batterystation_month.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQT6CFacCoEftq9FasBIFbm_FGzXSc5z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## battery data

# importing data
df_battery = pd.read_csv("../../01-scraping_Gogoro/output/gostations_cleaned.csv")
df_battery['id'] = df_battery.index

df_battery = df_battery.rename(columns={'status': 'current_status'})

# converting time to month
for i in range(1, 5):
    df_battery[f'activate_month{i}'] = pd.to_datetime(df_battery[f'activate_time{i}']).dt.to_period('M')
for i in range(1, 3):
    df_battery[f'remove_month{i}'] = pd.to_datetime(df_battery[f'remove_time{i}']).dt.to_period('M')

df_battery.head()

df_battery[df_battery['nBatteries'].isna()]

# number of stations with missing battery number
print(len(df_battery[df_battery['nBatteries'].isnull()]['id'].unique()))

# number of all stations
print(len(df_battery['id'].unique()))

# percent of stations with missing battery number
print(len(df_battery[df_battery['nBatteries'].isnull()]['id'].unique())/len(df_battery['id'].unique()))

# observing number of stations missing battery data by county
# Group by 'county'
county_stats = df_battery.groupby('county').agg(
    # Count the number of unique stations per county
    number_station=('id', 'nunique'),

    # Count the number of missing 'value_a' per county
    nbattery_missing=('nBatteries', lambda x: x.isna().sum())
).reset_index()

# Calculate percent_missing
county_stats['percent_missing'] = (county_stats['nbattery_missing'] / county_stats['number_station']) * 100

# filtering the counties
metros = ['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市']
metro_county_stats = county_stats[county_stats['county'].isin(metros)]

# sorting counties
metro_county_stats['county'] = pd.Categorical(metro_county_stats['county'], categories=metros, ordered=True)
metro_county_stats = metro_county_stats.sort_values('county').reset_index(drop=True)

total_stations = metro_county_stats['number_station'].sum()
total_missing = metro_county_stats['nbattery_missing'].sum()
percent_missing_total = (total_missing / total_stations) * 100

total_row = pd.DataFrame({
    'county': ['Total'],
    'number_station': [total_stations],
    'nbattery_missing': [total_missing],
    'percent_missing': [percent_missing_total]
})

metro_county_stats = pd.concat([metro_county_stats, total_row], ignore_index=True)

# Round the 'percent_missing' column to 1 decimal place
metro_county_stats['percent_missing'] = metro_county_stats['percent_missing'].apply(lambda x: f"{x:.1f}")

# Replace underscores with LaTeX-safe character sequence
metro_county_stats.columns = ['county', '\# stations', '\# missing', '\% missing']

# metro_county_stats.to_latex('../output/table/missing_battery.tex', index=False, column_format='lrrr')

# Create DataFrames for activation and deactivation events
activate_events = pd.melt(df_battery, id_vars=['id'],
                  value_vars=['activate_time1', 'activate_time2', 'activate_time3', 'activate_time4'],
                  var_name='event', value_name='datetime')
remove_events = pd.melt(df_battery, id_vars=['id'],
                  value_vars=['remove_time1', 'remove_time2'],
                  var_name='event', value_name='datetime')

# Concatenate activation and deactivation DataFrames
events = pd.concat([activate_events, remove_events])

# Convert datetime to quarter
events['month'] = pd.to_datetime(events['datetime']).dt.to_period('M')
events['datetime'] = pd.to_datetime(events['datetime'])

# Sort events by id and datetime
events = events.sort_values(by=['id', 'datetime'])

# Group by 'id' and 'quarter' and extract the first and last observations
firstlast = events.groupby(['id', 'month']).agg(
    first=('event', 'first'),
    last=('event', 'last')
).reset_index()

# Find the status in the beginning of the quarter and the end of the quarter
firstlast['start_status'] = (firstlast['first'].str.startswith(('remove'))).astype(int)
# if the first event is remove, then the station must be initially active
firstlast['end_status'] = (firstlast['last'].str.startswith('activate')).astype(int)

firstlast
# firstlast[(firstlast['start_status']==1) & (firstlast['end_status']==0) & (firstlast['first']=='deactivate_time1')]

# Create a DataFrame with all quarters for each id
all_quarters = pd.DataFrame(
    {'month': pd.period_range(start=events['month'].min(), end=events['month'].max(), freq='M')}
)
# Repeat each id for all quarters
all_quarters = all_quarters.assign(key=1).merge(pd.DataFrame({'key': [1]*len(events['id'].unique()), 'id': events['id'].unique()})).drop('key', axis=1)

# Merge with events DataFrame to fill missing quarters
stationstatus = pd.merge(all_quarters, firstlast[['month', 'id', 'start_status', 'end_status']], on=['month', 'id'], how='left')

# Fill the status by start and end status
stationstatus['end_status'] = stationstatus.groupby('id')['end_status'].ffill()
stationstatus['start_status'] = stationstatus.groupby('id')['start_status'].bfill()
stationstatus['status'] = stationstatus.groupby('id')['end_status'].fillna(stationstatus['start_status'])

stationstatus = stationstatus[['id', 'month', 'status']]

nstation = stationstatus.groupby('id').head(1).shape[0]
nstation_nostatus = stationstatus[stationstatus['status'].isna()].groupby('id').head(1).shape[0]

# merging back to the battery station info
stationstatus = stationstatus.merge(df_battery[['id', 'Name', 'current_status', 'nBatteries', 'districtid', 'county', 'district']], on='id', how='left')
## uncomment the below line to see the stations with no status changes and an "inactive" current status
# stationstatus[(stationstatus['status'].isna()) & (stationstatus['current_status'].str.contains('建置中'))].groupby('id').head(1)

# Fill the missing status with the current status
cond = stationstatus['current_status'] == "已啟用"
stationstatus['status'] = stationstatus['status'].fillna(cond.map({True: 1, False: 0}))

stationstatus = stationstatus.sort_values(by=['county', 'district', 'month'])
stationstatus = stationstatus.reset_index(drop=True)
stationstatus

# number of stations with missing battery number during any active month
print(len(stationstatus[(stationstatus['nBatteries'].isnull()) & (stationstatus['status']==1)]['id'].unique()))

# number of stations that was ever active
print(len(stationstatus[(stationstatus['status']==1)]['id'].unique()))

# divided
print(len(stationstatus[(stationstatus['nBatteries'].isnull()) & (stationstatus['status']==1)]['id'].unique())/len(stationstatus[(stationstatus['status']==1)]['id'].unique()))

# observing number of stations missing battery data by county, but restrict it to stations ever active
stations_ever_active = stationstatus[(stationstatus['status']==1)]['id'].unique()
df_battery_active = df_battery[df_battery['id'].isin(stations_ever_active)]

# Group by 'county'
county_stats = df_battery_active.groupby('county').agg(
    # Count the number of unique stations per county
    number_station=('id', 'nunique'),

    # Count the number of missing 'value_a' per county
    nbattery_missing=('nBatteries', lambda x: x.isna().sum())
).reset_index()

# Calculate percent_missing
county_stats['percent_missing'] = (county_stats['nbattery_missing'] / county_stats['number_station']) * 100

# filtering the counties
metros = ['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市']
metro_county_stats = county_stats[county_stats['county'].isin(metros)]

# sorting counties
metro_county_stats['county'] = pd.Categorical(metro_county_stats['county'], categories=metros, ordered=True)
metro_county_stats = metro_county_stats.sort_values('county').reset_index(drop=True)

total_stations = metro_county_stats['number_station'].sum()
total_missing = metro_county_stats['nbattery_missing'].sum()
percent_missing_total = (total_missing / total_stations) * 100

total_row = pd.DataFrame({
    'county': ['Total'],
    'number_station': [total_stations],
    'nbattery_missing': [total_missing],
    'percent_missing': [percent_missing_total]
})

metro_county_stats = pd.concat([metro_county_stats, total_row], ignore_index=True)

# Round the 'percent_missing' column to 1 decimal place
metro_county_stats['percent_missing'] = metro_county_stats['percent_missing'].apply(lambda x: f"{x:.1f}")

metro_county_stats.columns = ['county', '\# stations', '\# missing', '\% missing']

# metro_county_stats.to_latex('../output/table/missing_battery_stations_ever_active.tex', index=False, column_format='lrrr')

# Aggregate the town-month level battery station count
stationstatus['nActiveBatteries'] = stationstatus['status'] * stationstatus['nBatteries']
stationstatus['ActiveWithDataBattery'] = stationstatus['status'] * (stationstatus['nBatteries'].notnull())
town_month = (stationstatus[['county','district','month','status','nActiveBatteries', 'ActiveWithDataBattery']]
                                  .groupby(['county', 'district', 'month']).sum().reset_index())
town_month = town_month.sort_values(by=['county', 'district', 'month']).reset_index(drop=True)

town_month['month'] = town_month['month'].astype(str)
# Create a pivot table to fill missing periods with 0
town_month = town_month.pivot_table(index=['county','district'], columns='month', values=['status', 'nActiveBatteries', 'ActiveWithDataBattery'], fill_value=0).reset_index()

# Reset the columns to be a MultiIndex and flatten them
town_month.columns = ['_'.join(map(str, col)).strip().replace('_NaT','') if type(col) is tuple else col for col in town_month.columns.values]
town_month = town_month.rename(columns={'county_': 'county', 'district_': 'district'})
# Melt the DataFrame
melted_town_month = pd.melt(town_month, id_vars=['county', 'district'],
                             value_vars=[col for col in town_month.columns if col.startswith('status_') or col.startswith('nActiveBatteries_') or col.startswith('ActiveWithDataBattery_')],
                             var_name='month_type', value_name='value')

# Split 'month_type' into 'month' and 'type'
melted_town_month[['type', 'month']] = melted_town_month['month_type'].str.split('_', n=1, expand=True)

# Drop the redundant 'month_type' column
melted_town_month = melted_town_month.drop(columns=['month_type'])

# pivoting by type
town_month_battery_and_status = melted_town_month.pivot_table(index=['county', 'district', 'month'], columns='type', values='value', aggfunc='first').reset_index()

# flatten the structure
town_month_battery_and_status.columns.name = None

town_month_battery_and_status['month'] = pd.to_datetime(town_month_battery_and_status['month'], format='%Y-%m').dt.to_period('M')

town_month_battery_and_status = town_month_battery_and_status.sort_values(by=['county', 'district', 'month']).reset_index(drop=True)

town_month_battery_and_status = town_month_battery_and_status.rename(columns={'status': 'nstation', 'nActiveBatteries': 'nbattery', 'ActiveWithDataBattery':'nstation_w_battery'})

# merging the df with a full panel of the districts

districts = pd.read_csv('../input/all_districts.csv')

districts['county_district'] = districts['county'] + districts['district']

months = town_month_battery_and_status['month'].unique()

full_index = pd.MultiIndex.from_product([(districts['county_district']), months], names=['county_district', 'month'])
full_df = pd.DataFrame(index=full_index).reset_index().merge(districts, on='county_district')

town_month_battery_and_status['county_district'] = town_month_battery_and_status['county'] + town_month_battery_and_status['district']

merged = town_month_battery_and_status.merge(full_df, on=['county_district', 'month'], how='outer')

for col in ('nstation', 'nstation_w_battery', 'nbattery'):
    merged[col] = merged[col].fillna(0)

merged[merged['county_x'].isnull()]

merged['county'] = merged['county_y']
merged['district'] = merged['district_y']

merged = merged[['county', 'district', 'month', 'nstation_w_battery', 'nbattery', 'nstation']]

merged

merged.to_csv('../output/batterystation_town_month.csv', index=False)

# Aggregate the county-month level battery station count
county_month_battery_and_status = town_month_battery_and_status.groupby(['county', 'month']).agg(nstation = ('nstation', 'sum'), nbattery = ('nbattery', 'sum')).reset_index()
county_month_battery_and_status = county_month_battery_and_status.sort_values(by=['county', 'month']).reset_index(drop=True)

county_month_battery_and_status.to_csv('../output/batterystation_county_month.csv', index=False)

county_month_battery_and_status

county_month_battery_and_status['month'] = county_month_battery_and_status['month'].dt.to_timestamp()

county_month_battery_and_status = county_month_battery_and_status[county_month_battery_and_status['county'].isin(['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市'])]
county_month_battery_and_status['county'] = county_month_battery_and_status['county'].replace(['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市'],
                                    ['Taipei', 'New Taipei', 'Taoyuan', 'Taichung', 'Tainan', 'Kaohsiung'])

!mkdir "../output/graph"

# Plot line graph
plt.figure(figsize=(10, 6))

# Plot each county separately
for county in county_month_battery_and_status['county'].unique():
    county_df = county_month_battery_and_status[county_month_battery_and_status['county'] == county]
    plt.plot(county_df['month'], county_df['nstation'], label=county, linewidth=2.5)


plt.xlabel('Year', fontsize=14)
plt.ylabel('Cumulative number of battery stations', fontsize=14)

# Increase font size of tick labels
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.legend()

plt.savefig("../output/graph/nstation_trend.png", dpi=300)

plt.show()

df_scooter_limited_month = df_scooter[(df_scooter['month'] >= pd.to_datetime('2018-08').to_period('M'))]

df_scooter_limited_month = df_scooter_limited_month.reset_index(drop=True)

df_scooter_limited_month['month'] = pd.to_datetime(df_scooter_limited_month['month'].map(str)).dt.to_period('M')

# Merge back to the scooter data
df = county_month_battery_and_status.merge(df_scooter_limited_month, on=['county', 'month'], how='outer')

# creating the cumulative sum of E-scooters
df['cumsum_nscooter'] = df.groupby('county')['nscooter'].cumsum()

# Focusing on only the 6 major cities
df = df[df['county'].isin(['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市'])]
df['county'] = df['county'].replace(['臺北市', '新北市', '桃園市', '臺中市', '臺南市', '高雄市'],
                                    ['Taipei', 'New Taipei', 'Taoyuan', 'Taichung', 'Tainan', 'Kaohsiung'])

# Sum the value for all counties by month
monthly_sum = df.groupby("month")["nscooter"].sum().reset_index()

# Plot the time series
plt.figure(figsize=(10, 6))
plt.plot(monthly_sum["month"].dt.to_timestamp(), monthly_sum["nscooter"], marker="o", color="green", linewidth=2)
plt.title("Monthly total E-scooter sales across 6 cities", fontsize=16, fontweight='bold')
plt.xticks(rotation=45)  # Rotate month labels if needed
plt.tight_layout()
plt.savefig("../output/graph/monthly_escooter_sales_6_cities.png", dpi=300)  # Save the plot
plt.show()

# Plot line graph for the accumulated number of E-scooters
plt.figure(figsize=(10, 6))

for id_value, group_data in df.groupby('county'):
    plt.plot(group_data['month'].dt.to_timestamp(), group_data['cumsum_nscooter'], label=f'{id_value}', linewidth=2.5)

plt.xlabel('Month', fontsize=14)
plt.ylabel('Cumulative number of E-scooters', fontsize=14)

# Increase font size of tick labels
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.legend()

plt.savefig("../output/graph/nscooter_trend.png", dpi=300)

plt.show()

# Plot line graph
plt.figure(figsize=(10, 6))

for id_value, group_data in df.groupby('county'):
    plt.plot(group_data['month'].dt.to_timestamp(), group_data['nstation'], label=f'{id_value}', linewidth=2.5)

plt.xlabel('Month', fontsize=14)
plt.ylabel('Cumulative number of battery stations', fontsize=14)

# Increase font size of tick labels
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.legend()

plt.savefig("../output/graph/nstation_trend.png", dpi=300)

plt.show()

df['year'] = df['month'].dt.year
df_yearly = df.groupby(['county', 'year']).tail(1)
df_yearly['year'] = pd.to_datetime(df['year'], format='%Y')

# Plot line graph
plt.figure(figsize=(10, 6))

for id_value, group_data in df_yearly.groupby('county'):
    plt.plot(group_data['year'].apply(lambda x: x.year).astype(str), group_data['nstation'], label=f'{id_value}', linewidth=2.5)

plt.xlabel('Year', fontsize=14)
plt.ylabel('Cumulative number of battery stations', fontsize=14)

# Increase font size of tick labels
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.legend()

plt.savefig("../output/graph/nstation_yearly_trend.png", dpi=300)

plt.show()

for city in ('Taipei', 'New Taipei', 'Taoyuan', 'Taichung', 'Tainan', 'Kaohsiung'):

    # Plot line graph
    plt.figure(figsize=(10, 6))

    plt.scatter(df[df['county'] == city]['nstation'], df[df['county'] == city]['cumsum_nscooter'])
    plt.xlabel('Number of battery stations', fontsize=14)
    plt.ylabel('cumulative number of e-scooters', fontsize=14)
    plt.title(city, fontsize=16)

    # Increase font size of tick labels
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)

    plt.savefig(f"../output/graph/{city}_nscooter_nstation.png", dpi=300)

    plt.show()